import { useEffect, useState, } from "react";
import Sortable from "sortablejs";

const Sort_build = () => {
    const charactersArray = [
        "Abomination,憤怒魔像",
        "Absorbing Man,吸收人",
        "Agent Venom,特工毒液",
        "America Chavez,美國小姐",
        "Apocalypse,天啟",
        "Ares,阿瑞斯",
        "Beast,野獸",
        "Black Knight,黑騎士",
        "Black Panther,黑豹",
        "Blade,刀鋒戰士",
        "Bullseye,靶眼",
        "Captain America,美國隊長",
        "Carnage,屠殺",
        "Colossus,鋼人",
        "Crescent,弦月",
        "Crossbones,交叉骨",
        "Daken,達肯",
        "Deathlok,死亡戰機",
        "Doctor Octopus,章魚博士",
        "Drax,毀滅者德克斯",
        "Giant-Man,巨人",
        "Gilgamesh,吉爾伽美什",
        "Gladiator,角鬥士",
        "Goliath,巨人歌利亞",
        "Gorgon,石像鬼",
        "Gorilla-Man,猩猩人",
        "Groot,格魯特",
        "Hogun,霍根",
        "Hope Summers,希望·薩莫斯",
        "Hulk,綠巨人浩克",
        "Hulk (Amadeus Cho),浩克（阿馬迪斯·趙）",
        "Hulkling,浩克林",
        "Iron Fist,鐵拳俠",
        "Iron Man Mark 44 (Hulkbuster),鋼鐵人 浩克破壞者",
        "Jessica Jones,潔西卡·瓊斯",
        "Juggernaut,紅坦克",
        "Killmonger,齊爾蒙格",
        "Kingpin,金霸王",
        "Lizard,蜥蜴人",
        "Luke Cage,盧克·凱奇",
        "M'Baku,姆巴庫",
        "Man-Thing,沼澤怪物",
        "Minn-Erva,米奈娃",
        "Molten Man,熔岩人",
        "Moon Knight,月光騎士",
        "Morbius,活吸血鬼",
        "Mister Fantastic,驚奇先生",
        "Ms. Marvel (Kamala Khan),驚奇少女（卡瑪拉·克汗）",
        "Namor,納摩",
        "Nebula,星雲",
        "Omega Red,紅色歐米茄",
        "Punisher,制裁者",
        "Red Guardian,紅色守衛者",
        "Red Hulk,紅浩克",
        "Red She-Hulk,紅女浩克",
        "Rhino,犀牛人",
        "Sabretooth,劍齒虎",
        "Sandman,沙人",
        "Scream,尖叫女妖",
        "Shang-Chi,尚氣",
        "She-Hulk,女浩克",
        "Sif,希芙",
        "Skurge,屠殺者史庫奇",
        "Sword Master,劍齒虎（劍士）",
        "Taskmaster,模仿大師",
        "The Thing,石頭人",
        "Titania,泰坦妮亞",
        "Toxin,毒素",
        "Ulik,尤利克",
        "Valkyrie,女武神",
        "Venom,猛毒",
        "Volstagg,沃斯塔格",
        "War Tiger,戰虎",
        "Warpath,戰路",
        "Warwolf,戰狼",
        "White Tiger,白虎",
        "Wolverine,金鋼狼",
        "Adam Warlock,亞當術士",
        "Ancient One,古一",
        "Baron Mordo,魔多男爵",
        "Bishop,畢肖普",
        "Blue Dragon,青龍",
        "Cable,電索",
        "Captain America (Sharon Rogers),美國隊長（莎倫·羅傑斯）",
        "Crystal,水晶",
        "Cyclops,獨眼龍",
        "Daisy Johnson,黛西·強森",
        "Dazzler,眩光女",
        "Doctor Strange,奇異博士",
        "Echo,迴聲",
        "Emma Frost,艾瑪·弗洛斯特",
        "Enchantress,魅惑魔女",
        "Gambit,牌王",
        "Havok,霹靂火",
        "Human Torch,浩克二代（霍夫）",
        "Hydro-Man,水人",
        "Iceman,冰人",
        "Inferno,煉獄火",
        "Invisible Woman,隱形女",
        "Iron Man,鋼鐵人",
        "Ironheart,鋼鐵心",
        "Jean Grey,琴·葛雷",
        "Jubilee,朱比莉",
        "Kaecilius,凱西利亞斯",
        "Kahhori,卡霍莉",
        "Kid Omega,小歐米茄",
        "Lash,拉什",
        "Lincoln Campbell,林肯·坎貝爾",
        "M.O.D.O.K.,魔多客",
        "Madelyne Pryor,瑪德琳·普萊爾",
        "Magik,秘客",
        "Magneto,萬磁王",
        "Malekith,瑪勒基斯",
        "Mantis,螳螂女",
        "Maximus,馬克西姆斯",
        "Mephisto,墨菲斯托",
        "Mister Sinister,神秘先生",
        "Moon Girl,月亮女孩",
        "Moonstone,月光石",
        "Mysterio,神秘客",
        "Negasonic Teenage Warhead,彈頭少女",
        "Phil Coulson,菲爾·寇森",
        "Polaris,北極星",
        "Professor X,X 教授",
        "Psylocke,靈蝶",
        "Rachel Summers,瑞秋·薩莫斯",
        "Red Skull,紅骷髏",
        "Rescue,救援者（小辣椒）",
        "Rocket Raccoon,火箭浣熊",
        "Scarlet Witch,緋紅女巫",
        "Sersi,瑟希",
        "Sister Grimm,妮可·米諾魯",
        "Songbird,音波女",
        "Spectrum,光譜",
        "Spider-Woman,蜘蛛女",
        "Star-Lord,星爵",
        "Storm,暴風女",
        "Stryfe,史崔夫",
        "Ulysses Klaue,尤利西斯·克勞",
        "Vision,幻視",
        "War Machine,戰爭機器",
        "Wasp,黃蜂女（珍·范戴茵）",
        "Wasp (Nadia Van Dyne),黃蜂女（娜迪亞·范戴茵）",
        "Weapon Hex,武器六號",
        "Wenwu,文武",
        "Whiplash,鞭鎚",
        "Wiccan,威肯",
        "Yellowjacket,黃衫俠",
        "Aero,氣旋女",
        "Agent 13,特工 13",
        "Angel,天使",
        "Ant-Man,蟻人",
        "Arachknight,蛛網騎士",
        "Baron Zemo,澤莫男爵",
        "Black Cat,黑貓",
        "Black Swan,黑天鵝",
        "Black Widow,黑寡婦",
        "Cassie Lang,凱西·朗",
        "Daredevil,夜魔俠",
        "Darkhawk,暗鷹",
        "Deadpool,死侍",
        "Domino,多米諾",
        "Electro,電光人",
        "Elektra,艾麗卡",
        "Elsa Bloodstone,艾爾莎·血石",
        "Falcon,獵鷹",
        "Fandral,范達爾",
        "Fantomex,幻影客",
        "Gamora,葛摩拉",
        "Ghost,幽靈",
        "Green Goblin,綠惡魔",
        "Gwenpool,格溫潘",
        "Hawkeye,鷹眼",
        "Hawkeye (Kate Bishop),鷹眼（凱特·畢曉普）",
        "Hellcat,地獄貓",
        "Ikon,艾康",
        "Karnak,卡納克",
        "Katy,凱蒂",
        "Kid Kaiju,怪獸小子",
        "Kingo,京戈",
        "Kitty Pryde,凱蒂·普萊德",
        "Korath,克羅納",
        "Kraven The Hunter,獵人克雷文",
        "Luna Snow,白狐·雪莉（露娜·雪）",
        "Makkari,馬卡瑞",
        "Misty Knight,蜜絲蒂·奈特",
        "Mystique,魔形女",
        "Nick Fury,尼克·福瑞",
        "Nightcrawler,夜行者",
        "Quicksilver,快銀",
        "Rogue,俠盜",
        "Scarlet Spider,猩紅蜘蛛",
        "Scorpion,蠍子",
        "Shuri,舒莉",
        "Silk,絲",
        "Sin,辛",
        "Spider-Gwen,蜘蛛格溫",
        "Spider-Man,蜘蛛人",
        "Spider-Man (Miles Morales),蜘蛛人（邁爾斯·莫拉雷斯）",
        "Spider-Man 2099,蜘蛛人2099",
        "Spot,斑點人",
        "Squirrel Girl,松鼠女孩",
        "Sun Bird,太陽鳥",
        "Viper,毒蛇",
        "Vulture,禿鷹",
        "Wave,海嘯女",
        "White Fox,白狐",
        "Winter Soldier,冬日戰士",
        "Wong,王",
        "X-23,X-23",
        "Yelena Belova,葉蓮娜·貝洛娃",
        "Yondu,揚杜",
        "Angela,安潔拉",
        "Anti-Man,反蟻人",
        "Beta Ray Bill,貝塔·雷·比爾",
        "Black Bolt,黑閃電",
        "Black Dwarf,黑矮人",
        "Blue Marvel,藍魔",
        "Captain Marvel,驚奇隊長",
        "Clea,克莉亞",
        "Corvus Glaive,科爾維斯·格雷夫",
        "Dormammu,多瑪姆",
        "Destroyer,破壞者",
        "Doctor Doom,末日博士",
        "Doctor Voodoo,巫毒博士",
        "Ebony Maw,伊波尼·莫",
        "Exodus,出埃及記",
        "Ghost Panther,幽靈黑豹",
        "Ghost Rider,鬼騎士",
        "Ghost Rider (Robbie Reyes),鬼騎士（羅比·雷耶斯）",
        "Gorr,戈爾",
        "Heimdall,海姆達爾",
        "Hela,海拉",
        "Hellstorm,地獄風暴",
        "Hyperion,超凡者",
        "Ikaris,伊卡利斯",
        "Iron Hammer,鋼鐵鎚",
        "Kang The Conqueror,康征服者",
        "Knull,諾爾",
        "Loki,洛基",
        "Medusa,美杜莎",
        "Molecule Man,分子人",
        "Morgan Le Fay,摩根·勒菲",
        "Nova (Richard Rider),新星（理查·萊德）",
        "Nova (Sam Alexander),新星（山姆·亞歷山大）",
        "Odin,奧丁",
        "Phyla-Vell,菲拉-維爾",
        "Proxima Midnight,普羅克西瑪·午夜",
        "Quasar (Wendell Vaughn),量子女（溫德爾·沃恩）",
        "Quasar (Avril Kincaid),量子女（艾芙瑞爾·金凱德）",
        "Ronan,羅南",
        "Satana,撒塔納",
        "Sentinel,哨兵",
        "Sentry,哨兵者",
        "Shadow Shell,暗影殼",
        "Silver Surfer,銀河守護者",
        "Singularity,奇異點",
        "Slapstick,滑稽人",
        "Supergiant,超巨",
        "Sylvie,希爾維",
        "Thane,撒恩",
        "Thanos,薩諾斯",
        "Thena,瑟娜",
        "Thor,索爾",
        "Thor (Jane Foster),索爾（珍·福斯特）"
    ];
    console.log(charactersArray);




    const [sortText, setSortText] = useState(charactersArray)

    useEffect(() => {

        new Sortable(test1, {
            group: {
                name: 'char',
                put: true
            },
            animation: 150,
            ghostClass: 'blue-background-class'
        });
        new Sortable(test2, {
            group: {
                name: 'char',
                put: true
            },
            animation: 150,
            ghostClass: 'blue-background-class'
        });
    }, [])





    return (
        <>
            <div id="text_block">
                <h2>拖曳</h2>
                <div id="test1">
                    {
                        sortText.map((item, index) => {
                            return (
                                <div className="sort_item" key={index}>{item}</div>
                            )
                        })
                    }
                </div>
                <div id="test2">
                    {
                        sortText.map((item, index) => {
                            return (
                                <div className="sort_item" key={index}>{item}</div>
                            )
                        })
                    }
                </div>
            </div>
        </>
    )
}
export default Sort_build;
